apiVersion: v1
kind: Pod
metadata:
  name: rust-service-deployment
  labels:
    app: node-hello-world-app
spec:
  containers:
  - name: rust
    image: 692527062901.dkr.ecr.eu-west-1.amazonaws.com/rust_gba:latest
    volumeMounts:
      - name: sourcecode 
        mountPath: "/data/gba/examples"
      - name: target 
        mountPath: "/data/gba/target"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1024m"
  volumes:
    - name: sourcecode
      hostPath:
        path: "/mnt/project_storage/sources/555"
    - name: target
      hostPath:
        path: "/mnt/project_storage/build/555"
  imagePullSecrets:
    - name: regcred
  restartPolicy: Never
  terminationGracePeriodSeconds: 60